export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const PRODUCT_CREATE_REVIEW_REQUEST = "PRODUCT_CREATE_REVIEW_REQUEST";
export const PRODUCT_CREATE_REVIEW_SUCCESS = "PRODUCT_CREATE_REVIEW_SUCCESS";
export const PRODUCT_CREATE_REVIEW_FAIL = "PRODUCT_CREATE_REVIEW_FAIL";
export const PRODUCT_CREATE_REVIEW_RESET = "PRODUCT_CREATE_REVIEW_RESET";

export const REVIEW_LIST_REQUEST = "REVIEW_LIST_REQUEST";
export const REVIEW_LIST_SUCCESS = "REVIEW_LIST_SUCCESS";
export const REVIEW_LIST_FAIL = "REVIEW_LIST_FAIL";

export const REVIEW_CHECKED_REQUEST = "REVIEW_CHECKED_REQUEST";
export const REVIEW_CHECKED_SUCCESS = "REVIEW_CHECKED_SUCCESS";
export const REVIEW_CHECKED_FAIL = "REVIEW_CHECKED_FAIL";

export const PRODUCT_LIST_FORYOU_REQUEST = "PRODUCT_LIST_FORYOU_REQUEST";
export const PRODUCT_LIST_FORYOU_SUCCESS = "PRODUCT_LIST_FORYOU_SUCCESS";
export const PRODUCT_LIST_FORYOU_FAIL = "PRODUCT_LIST_FAIL";

export const VIEWS_DETAILS_REQUEST = "VIEWS_DETAILS_REQUEST";
export const VIEWS_DETAILS_SUCCESS = "VIEWS_DETAILS_SUCCESS";
export const VIEWS_DETAILS_FAIL = "VIEWS_DETAILS_FAIL";
